# Copyright 2021 BenchSci Analytics Inc. All rights reserved.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.



# This shows how you might create macros for the autogenerated rules. You should probably not use these rules directly

load("@bazel_skylib//lib:sets.bzl", "sets")
load("@build_bazel_rules_nodejs//:index.bzl", _js_library = "js_library")
load("@build_bazel_rules_nodejs//:index.bzl", _copy_to_bin = "copy_to_bin")
load("@npm//jest:index.bzl", "jest", _jest_test = "jest_test")
load("@npm//@bazel/typescript:index.bzl", _ts_project = "ts_project")

def web_assets(name, srcs, **kwargs):
    tags = kwargs.pop("tags", [])
    tags.append("manual")
    native.filegroup(
        name = name,
        srcs = srcs,
        **kwargs,
    )

def copy_to_bin(name, srcs, **kwargs):
    tags = kwargs.pop("tags", [])
    tags.append("manual")
    _copy_to_bin(name = name, srcs = srcs, tags = tags, **kwargs)

def js_library(name, srcs, **kwargs):
    deps = kwargs.pop("deps", [])
    data = kwargs.pop("data", [])
    tags = kwargs.pop("tags", [])
    tags.append("manual")

    _js_library(name = name, srcs = srcs, tags = tags, deps = deps + data, **kwargs)

def ts_project(name, srcs, **kwargs):
    deps = kwargs.pop("deps", []) + kwargs.pop("dynamic_deps", [])
    data = kwargs.pop("data", [])
    tags = kwargs.pop("tags", [])
    
    tags.append("manual")
    _ts_project(
        name = name,
        srcs = srcs + data,
        deps = deps,
        tags = tags,
        **kwargs
    )

def jest_test(name, srcs, **kwargs):
    "A macro around the autogenerated jest_test rule"
    templated_args = [
        "--no-cache",
        "--no-watchman",
        "--colors",
        "--runInBand",  # Bazel already does parallelization.
        "--verbose",
    ]

    deps = kwargs.pop("deps", [])
    data = kwargs.pop("data", [])
    srcs = srcs + data
    tags = kwargs.pop("tags", [])
    flaky = kwargs.pop("flaky", False)

    _jest_test(
        name = name,
        data = data,
        tags = tags,
        templated_args = templated_args,
        flaky = flaky,
        **kwargs
    )

    # This rule is used specifically to update snapshots via `bazel run`
    jest(
        name = "%s.update" % name,
        data = data,
        tags = tags,
        templated_args = templated_args + ["-u"],
        **kwargs
    )
